AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless User API with Lambda + API Gateway

Globals:
  Function:
    Timeout: 10
    Runtime: python3.10

Resources:

  # API Gateway
  UserApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL

  # Lambda Function
  UserApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: user/   # your lambda source folder
      Events:
        GetUsers:
          Type: Api
          Properties:
            Path: /users
            Method: GET
            RestApiId: !Ref UserApi
        GetUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: GET
            RestApiId: !Ref UserApi

Outputs:

  UserApiUrl:
    Description: "Base URL of the User API"
    Value: !Sub "https://bvv8hrsnbc.execute-api.${AWS::Region}.amazonaws.com/Prod/"
